server:
    port: 8081

spring:
    application:
        name: user-service
    cloud:
        vault:
            uri: http://localhost:8200
            token: ${VAULT_TOKEN}
            kv:
                enabled: true
                backend: secret
                default-context: spring-boot-lms
            scheme: http
    config:
        import: vault://secret/spring-boot-lms
    datasource:
        url: ${vault.db_url}
        username: ${vault.db_username}
        password: ${vault.db_password}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect


#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
#        registerWithEureka: true
#        fetchRegistry: true
#
#    instance:
#        preferIpAddress: true
#        instanceId: ${spring.application.name}:${server.port}:${random.value}
#        leaseRenewalIntervalInSeconds: 5
#        leaseExpirationDurationInSeconds: 10
